name: Update Website Data

on:
    schedule:
      # Runs every day at 7:00AM UTC
      - cron:  '0 10 * * 2-0'
    workflow_dispatch:  # This line enables manual trigger

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements-github-actions.txt
      - name: Run fetch_data script
        env:
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
        run: python fetch_data.py
      - name: Commit files
        run: |
          git config --global user.email "o11ey@hotmail.com"
          git config --global user.name "opmarcfield"
          git add .
          git commit -m "Update data" -a || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
